# Don't edit this file
#
# It was auto generated by CMake from module.json which should be edited instead

set(DEPENDENT_NAP_MODULES napmidi napparameter)
set(DEEP_DEPENDENT_NAP_MODULES napmidi napparameter napscene napcolor napmath)
set(DEEP_DEPENDENT_RPATHS )
